[package]
name = "error-handling"
version = "0.0.0"
workspace = "../"
edition = "2021"
publish = false

[dependencies]
rocket = { path = "../../core/lib", features = ["json"] }
transient = { path = "/code/matthew/transient" }
